### ISSUE TITLE
run on windows 

### ISSUE THREAD

**Issue by MarcoSchaar** [zanetworker/dockument#5]
Hi,
while testing on window there are few question that might be not right covered in readme.
release file downloaded for Windows … Needs rename to "exe" afterwards?!

when running like this 

dockument-latest-windows-amd64.exe help

I got

[31mFATA[0m[0000] Could not create Dockument, dockertemplate path  ( .../src/github.com/zanetworker/dockument/configs/dockumentation.tpl ) is invalid

Any hint for usage?

**Comment by zanetworker** [comment]
I think you need to rebuild the binaries, try following the instructions on the README: 
```
git clone https://github.com/zanetworker/dockument.git
cd dockument

# build dockument binary if you have go installed
make OS=<darwin|linux|windows> install
```

**Comment by MarcoSchaar** [comment]
Thanks for this hint.
Modified the makefile and had to install more than the mentioned prerequisits.
Sadly the make file does not create an exe file on Windows. 
after rename and start the following error comes up

[31mFATA[0m[0000] Could not create Dockument, dockertemplate path  ( C:\Go\bin/src/github.com/zanetworker/dockument/configs/dockumentation.tpl ) is invalid

what all is needed to Setup local enviroment?

**Comment by zanetworker** [comment]
it needs to find the template to create the Dockument for you. So it is searching for the path you have above and it does not seem to find it. I have not tested it with windows unfortunately, but if it can find the dockumentation.tpl file it should be able to start. If not, maybe it needs a patch to work with windows, would be happy to accept a PR in that case :)

**Comment by MarcoSchaar** [comment]
Hi 
copied the cloned git repo to local GOPATH under src Folder, so it works.
thanks a lot

**Comment by zanetworker** [comment]
Gald it worked, happy to help!
